authorized_users:
  - kandrosov
  - acagnotta
  - Sayan-Dhani
  - prabhatsolanki
  - akhter-towsifa
  - vdamante

expected_headers:
  - "@cms-flaf-bot test"
  - "@cms-flaf-bot please test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) test"
  - "[@cms-flaf-bot](https://github.com/cms-flaf-bot) please test"

variables:
  HH_bbtautau_version: "main"
  FLAF_version: "default"
  Corrections_version: "default"
  HH_bbtautau_active: "1"
  HH_bbtautau_task: "FLAF.Analysis.tasks.HistPlotTask"
  HH_bbtautau_eras: "Run3_2022 Run3_2022EE Run3_2023 Run3_2023BPix"
  HH_bbtautau_args: "--branches 0 --test 1000"
  TEST_TIMEOUT: "4h"

gitlab_url: "https://gitlab.cern.ch/api/v4/projects/210600/trigger/pipeline"
gitlab_branch: "master"
