norm:
  PileUp_Lumi_MC:
    expression: weight_MC_Lumi_pu{scale}_rel  * final_weight
    name: CMS_pileup_{}
  MuonID_TightID:
    expression: weight_tau1_MuonID_SF_TightID_Trk{scale}_rel * weight_tau2_MuonID_SF_TightID_Trk{scale}_rel * final_weight
    name: MuonID_TightID
  MuonID_TightIDIso:
    expression: weight_tau1_MuonID_SF_LoosePFIso{scale}_rel * weight_tau2_MuonID_SF_LoosePFIso{scale}_rel * final_weight
    name: MuonID_TightIDIso
  trg_eTau_e:
    expression: weight_trgSF_eTau_eleg_{scale}_rel * final_weight
    name: trg_eTau_e_{}
  trg_eTau_tau:
    expression: weight_trgSF_eTau_tauleg_dm0_{scale}_rel * weight_trgSF_eTau_tauleg_dm1_{scale}_rel * weight_trgSF_eTau_tauleg_dm10_{scale}_rel * weight_trgSF_eTau_tauleg_dm11_{scale}_rel * final_weight
    name: trg_eTau_tau_{}
  trg_muTau_mu:
    expression: weight_trgSF_muTau_muleg_{scale}_rel * final_weight
    name: trg_muTau_mu_{}
  trg_muTau_tau:
    expression: weight_trgSF_muTau_tauleg_dm0_{scale}_rel * weight_trgSF_muTau_tauleg_dm1_{scale}_rel * weight_trgSF_muTau_tauleg_dm10_{scale}_rel * weight_trgSF_muTau_tauleg_dm11_{scale}_rel * final_weight
    name: trg_muTau_tau_{}
  trg_tauTau_tau:
    expression: weight_trgSF_tauTau_tauleg_dm0_dm0_{scale}_rel * weight_trgSF_tauTau_tauleg_dm0_dm1_{scale}_rel * weight_trgSF_tauTau_tauleg_dm0_dm10_{scale}_rel * weight_trgSF_tauTau_tauleg_dm0_dm11_{scale}_rel * weight_trgSF_tauTau_tauleg_dm1_dm0_{scale}_rel * weight_trgSF_tauTau_tauleg_dm1_dm1_{scale}_rel * weight_trgSF_tauTau_tauleg_dm1_dm10_{scale}_rel * weight_trgSF_tauTau_tauleg_dm1_dm11_{scale}_rel * weight_trgSF_tauTau_tauleg_dm10_dm0_{scale}_rel * weight_trgSF_tauTau_tauleg_dm10_dm1_{scale}_rel * weight_trgSF_tauTau_tauleg_dm10_dm10_{scale}_rel * weight_trgSF_tauTau_tauleg_dm10_dm11_{scale}_rel * weight_trgSF_tauTau_tauleg_dm11_dm0_{scale}_rel * weight_trgSF_tauTau_tauleg_dm11_dm1_{scale}_rel * weight_trgSF_tauTau_tauleg_dm11_dm10_{scale}_rel * weight_trgSF_tauTau_tauleg_dm11_dm11_{scale}_rel * final_weight
    name: trg_tauTau_tau_{}
  trg_tauTau_jet:
    expression: weight_trgSF_tauTau_jetleg_{scale}_rel * final_weight
    name: trg_tauTau_jet_{}
  trg_muMueMu:
    expression:  weight_trgSF_muMueMu_{scale}_rel * final_weight
    name: trg_muMueMu_{}
  trg_eE:
    expression: weight_trgSF_eE_{scale}_rel * final_weight
    name: trg_eE_{}

shape: # syst unc conventions here: https://gitlab.cern.ch/cms-analysis/general/systematics
  JES_Total:
    name: CMS_scale_j_{}
  JER:
    name: CMS_res_j_{}
