BaseModel:
  name: "Base Model"
  backgrounds:
    - TT
    - ttH
    - ggH
    - VBFH
    - VH
    - ST
    - DY
    - WtoLNu
    - VV
    - VVV

  signals:
    - GluGlutoHHto2B2Tau
  data:
    - Data
