BaseModel:
  name: "Base Model"
  backgrounds:
    - TT
    - ttH
    - ggH
    - VBFH
    - VH
    - ST
    - DY
    - WtoLNu
    - VV
    - VVV

  signals:
    - GluGlutoHHto2B2Tau
    - VBFHHto2B2Tau
  data:
    - Data


TestModel:
  name: "Test model for CI"
  signals:
    - custom_CI

TestModel:
  name: "Test model for CI"
  backgrounds:
    - custom_CI_Background
  signals: # WARNING: for 2024 no signal sample available, using a file from bbtt signals..
    - custom_CI_Signal
  data:
    - custom_CI_Data
