.DY_processors: &DY_processors
  - name: Stitcher
    module: FLAF.Processors.MCStitching
    class: MCStitcher
    config: FLAF/config/Processors/stitching_DY_amcatnlo_Vpt_NpNLO.yaml
    stages: [ AnaTuple, AnaTupleMerge ]
    dependency_level:
      AnaTuple: file
      AnaTupleMerge: process
