TT:
  name: "t#bar{t}"
  color: "kGreen-3"  # eliminates need for plot.yaml
  datasets:
    - TTto2L2Nu
    - TTtoLNu2Q
    - TTto4Q

TT_Inclusive:
  name: "t#bar{t} Inclusive"
  color: "kGreen-3"
  datasets:
    - TT

GluGlutoHHto2B2Tau:
  name: "GluGlutoHHto2B2Tau"
  color: "kBlack"
  is_meta_process: true
  meta_setup:
    dataset_name_pattern: GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_(\d+)  # GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00 # I don't know regex, good luck :P
    parameters: [ c2 ]
    process_name: GluGluToHHto2B2Tau_${c2}
    name_pattern: GluGluToHHto2B2Tau c2 ${c2} GeV
    to_plot: [ 0p00 ]
    plot_color: [ "kBlack" ]
  datasets:
    - GluGlutoHHto2B2Tau_kl_1p00_kt_1p00_c2_0p00

Data_Full:
  name: "Data"
  datasets:
    - EGamma_Run2022C
    - EGamma_Run2022D
    - Muon_Run2022C
    - Muon_Run2022D
    - SingleMuon_Run2022C
    - DoubleMuon_Run2022C
    - MuonEG_Run2022C
    - MuonEG_Run2022D

Data_EGamma:
  name: "Data EGamma"
  datasets:
    - EGamma_Run2022C
    - EGamma_Run2022D

Data_Muon:
  name: "Data Muon"
  datasets:
    - SingleMuon_Run2022C
    - DoubleMuon_Run2022C
    - Muon_Run2022C
    - Muon_Run2022D

Data_MuonEG:
  name: "Data MuonEG"
  datasets:
    - MuonEG_Run2022C
