#https://twiki.cern.ch/twiki/bin/viewauth/CMS/TauTrigger#Updates_for_2022_data_taking
ditau:
  channels:
    - tauTau
  path:
    - HLT_DoubleMediumDeepTauPFTauHPS35_L2NN_eta2p1
  legs:
    - offline_obj:
        cut: "{obj}_legType == Leg::tau && {obj}_pt > 40 && abs({obj}_eta) < 2.1"
      online_obj:
        cut: TrigObj_id==15 && (TrigObj_filterBits&8)!=0 && (TrigObj_filterBits&2048)!=0
      dRMatching: 0.4
      doMatching: True

ditaujet:
  channels:
    - tauTau
  path:
    - HLT_DoubleMediumDeepTauPFTauHPS30_L2NN_eta2p1_PFJet60
  legs:
    - offline_obj:
        cut: "{obj}_legType == Leg::tau && {obj}_pt > 35 && abs({obj}_eta) < 2.1"
      online_obj:
        cut: TrigObj_id==15 && (TrigObj_filterBits&8)!=0 && (TrigObj_filterBits&2048)!=0 & (TrigObj_filterBits&16384)!=0
      doMatching: True
    - offline_obj:
        cut: "{obj}_legType == Leg::jet && {obj}_pt > 60"
      online_obj:
        cut: TrigObj_id==1 && (TrigObj_filterBits&131072)!=0
      doMatching: True

mutau:
  channels:
    - muTau
  path:
    - HLT_IsoMu20_eta2p1_LooseDeepTauPFTauHPS27_eta2p1_CrossL1
  legs:
    - offline_obj:
        cut: "{obj}_legType == Leg::mu && {obj}_pt > 22 && abs({obj}_eta) < 2.1"
      online_obj:
        cut: TrigObj_id==13 && (TrigObj_filterBits&64)!=0 #&& TrigObj_pt>20
      doMatching: True
    - offline_obj:
        cut: "{obj}_legType == Leg::tau && {obj}_pt > 32 && abs({obj}_eta) < 2.1"
      online_obj:
        cut: TrigObj_id==15 && (TrigObj_filterBits&8)!=0  && (TrigObj_filterBits&8192)!=0
      doMatching: True

etau:
  channels:
    - eTau
  path:
    - HLT_Ele24_eta2p1_WPTight_Gsf_LooseDeepTauPFTauHPS30_eta2p1_CrossL1
  legs:
    - offline_obj:
        cut: "{obj}_legType == Leg::e && {obj}_pt > 26 && abs({obj}_eta) < 2.1"
      online_obj:
        cut: TrigObj_id==11 && (TrigObj_filterBits&128)!=0 #&& TrigObj_pt>24
      doMatching: True
    - offline_obj:
        cut: "{obj}_legType == Leg::tau && {obj}_pt > 35 && abs({obj}_eta) < 2.1"
      online_obj:
        cut:  TrigObj_id==15 && (TrigObj_filterBits&8)!=0 && (TrigObj_filterBits&4096)!=0
      doMatching: True

singleMu:
  channels:
    - muMu
    - eMu
    - mu
  path:
    - HLT_IsoMu24
  legs:
    - offline_obj:
        cut:  "{obj}_legType == Leg::mu && {obj}_pt > 26"# {obj}_pt > 26 && abs({obj}_eta) < 2.4
      online_obj:
        cut: TrigObj_id == 13 && (TrigObj_filterBits&8)!=0
      doMatching: True

singleEle:
  channels:
    - eMu
    - eE
    - e
  path:
    - HLT_Ele30_WPTight_Gsf
  legs:
    - offline_obj:
        cut: "{obj}_legType == Leg::e && {obj}_pt > 32"# {obj}_pt > 32 && abs({obj}_eta) < 2.4
      online_obj:
        cut: TrigObj_id == 11 && (TrigObj_filterBits&2)!=0
      doMatching: True

####################################
# MET:
#     channels:
#       - tauTau
#       - muTau
#       - eTau
#       - eMu
#       - muMu
#       - eE
#     path:
#       - HLT_PFMETNoMu120_PFMHTNoMu120_IDTight
#     legs:
#       - offline_obj:
#           type: MET
#           cut: metnomu_pt > 150
#         doMatching: False

# singleTau:
#     channels:
#       - tauTau
#       - muTau
#       - eTau
#     path:
#       - HLT_LooseDeepTauPFTauHPS180_L2NN_eta2p1
#     legs:
#       - offline_obj:
#           type: Tau
#           cut: v_ops::pt(Tau_p4) > 190 && abs(v_ops::eta(Tau_p4)) < 2.1
#         online_obj:
#           cut: TrigObj_id == 15 && (TrigObj_filterBits&8)!=0 && (TrigObj_filterBits&512)!=0
#         doMatching: True